### ISSUE TITLE
Gift up deduct from sub total instead of total

### ISSUE THREAD

**Issue by diverds1992** [igniter-labs/ti-ext-giftup#1]
**Expected behavior:**
(Gift up should deduct from total instead of sub total)

**Actual behavior:**
Gift up deduct from sub total instead of total)

**Reproduce steps:**
()

**Version:**
(latest)

**Additional Information:**
(I move “gift up” to the last position under System > Settings > Cart Settings, the other expenses such as delivery costs and transaction fees still need to be paid.)

**Comment by sampoyigi** [comment]
What happens if you drag the gift up cart condition just before delivery and transaction fees. Share a screenshot of your cart condition settings.

**Comment by diverds1992** [comment]
![Schermafbeelding 2023-09-08 om 14 49 06](https://github.com/igniter-labs/ti-ext-giftup/assets/78227663/b288522b-7787-4489-b501-d89f24c9e2ae)
Setting last position
![Schermafbeelding 2023-09-08 om 14 50 29](https://github.com/igniter-labs/ti-ext-giftup/assets/78227663/b61785cb-d206-4219-a388-1795f519086d)
cart last position
![Schermafbeelding 2023-09-08 om 14 50 57](https://github.com/igniter-labs/ti-ext-giftup/assets/78227663/a4c80ca2-9508-456c-969e-fc70d518328f)
Setting first position
![Schermafbeelding 2023-09-08 om 14 50 52](https://github.com/igniter-labs/ti-ext-giftup/assets/78227663/75e3c280-e537-49e9-831c-e6837a559f64)
Cart first position
